# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/focusroot
spring.datasource.username=postgres
spring.datasource.password=262712
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=focusroot-secret-key-must-be-at-least-32-characters-long

# Server
server.port=8080
